name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Homebrew
      run: brew update

    - name: Run Regression Tests
      run: tests/run_tests.sh

    - name: Verify CLI Installation (Homebrew mode)
      run: |
        # Workaround: Create a local tap to satisfy Homebrew in CI
        brew tap-new local/test --no-git
        cp Formula/better-anonymity.rb $(brew --repo local/test)/Formula/
        brew install --HEAD local/test/better-anonymity
        
        better-anonymity help
        b-a help

    - name: Verify CLI Installation (Pip mode)
      run: |
        pip3 install .
        python3 -m better_anonymity help
        b-a help
